//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gorevler
    {
        public int gor_Id { get; set; }
        public string gor_kod { get; set; }
        public string gor_carikod { get; set; }
        public string gor_personelkod { get; set; }
        public string gor_icerik { get; set; }
        public string gor_konu { get; set; }
        public string gor_not { get; set; }
        public Nullable<int> gor_sirano { get; set; }
        public string gor_durumkod { get; set; }
        public Nullable<System.DateTime> gor_create_date { get; set; }
        public Nullable<System.DateTime> gor_lastup_date { get; set; }
        public Nullable<System.DateTime> gor_bitis_date { get; set; }
        public string gor_tipi { get; set; }
        public Nullable<bool> gor_aktif { get; set; }
    
        public virtual Cari_Yetkilileri Cari_Yetkilileri { get; set; }
        public virtual Cariler Cariler { get; set; }
        public virtual Durumlar Durumlar { get; set; }
        public virtual İliskiler İliskiler { get; set; }
    }
}
