//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class İliskiler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public İliskiler()
        {
            this.Gorevler = new HashSet<Gorevler>();
        }
    
        public int ilis_Id { get; set; }
        public string ilis_kodu { get; set; }
        public string ilis_adi { get; set; }
        public Nullable<System.DateTime> ilis_create_date { get; set; }
        public Nullable<System.DateTime> ilis_lastup_date { get; set; }
        public Nullable<bool> ilis_aktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gorevler> Gorevler { get; set; }
    }
}
