//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class İlceler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public İlceler()
        {
            this.Cari_Adresleri = new HashSet<Cari_Adresleri>();
        }
    
        public int ilce_Id { get; set; }
        public string ilce_kod { get; set; }
        public string ilce_isim { get; set; }
        public string ilce_ilkodu { get; set; }
        public Nullable<System.DateTime> ilce_create_date { get; set; }
        public Nullable<System.DateTime> ilce_lastup_date { get; set; }
        public Nullable<bool> ilce_aktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cari_Adresleri> Cari_Adresleri { get; set; }
    }
}
