//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail_Bilgileri
    {
        public int mail_id { get; set; }
        public string mail_mailsunucu { get; set; }
        public string mail_adresi { get; set; }
        public string mail_sifre { get; set; }
        public string mail_ccadresi { get; set; }
        public string mail_useradi { get; set; }
        public Nullable<int> mail_portı { get; set; }
        public Nullable<bool> mail_sll { get; set; }
    }
}
