//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cariler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cariler()
        {
            this.Cari_Yetkilileri = new HashSet<Cari_Yetkilileri>();
            this.Gorevler = new HashSet<Gorevler>();
        }
    
        public int cari_Id { get; set; }
        public string cari_kod { get; set; }
        public string cari_unvan { get; set; }
        public string cari_vergino { get; set; }
        public string cari_vergidaire_adi { get; set; }
        public Nullable<System.DateTime> cari_create_date { get; set; }
        public Nullable<System.DateTime> cari_lastup_date { get; set; }
        public Nullable<bool> cari_aktif { get; set; }
    
        public virtual Cari_Adresleri Cari_Adresleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cari_Yetkilileri> Cari_Yetkilileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gorevler> Gorevler { get; set; }
    }
}
