//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cari_Adresleri
    {
        public int cariadr_Id { get; set; }
        public string cariadr_carikod { get; set; }
        public string cariadr_ulke { get; set; }
        public string cariadr_il { get; set; }
        public string cariadr_ilce { get; set; }
        public string cariadr_adres { get; set; }
        public string cariadr_websitesi { get; set; }
        public Nullable<bool> cariadr_aktif { get; set; }
    
        public virtual Cariler Cariler { get; set; }
        public virtual İlceler İlceler { get; set; }
        public virtual İller İller { get; set; }
        public virtual Ulkeler Ulkeler { get; set; }
    }
}
