//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cari_Yetkilileri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cari_Yetkilileri()
        {
            this.Gorevler = new HashSet<Gorevler>();
        }
    
        public int cariyet_Id { get; set; }
        public string cariyet_CariKod { get; set; }
        public string cariyet_PersonelKod { get; set; }
        public string cariyet_PersonelFullName { get; set; }
        public string cariyet_personelmail { get; set; }
        public string cariyet_personeltipi { get; set; }
        public Nullable<System.DateTime> cariyet_create_date { get; set; }
        public Nullable<System.DateTime> cariyet_lastup_date { get; set; }
        public Nullable<bool> cariyet_aktif { get; set; }
    
        public virtual Cariler Cariler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gorevler> Gorevler { get; set; }
    }
}
