//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enti
{
    using System;
    using System.Collections.Generic;
    
    public partial class İller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public İller()
        {
            this.Cari_Adresleri = new HashSet<Cari_Adresleri>();
        }
    
        public int il_Id { get; set; }
        public string il_ilkod { get; set; }
        public string il_ilisim { get; set; }
        public string il_ulkekod { get; set; }
        public Nullable<System.DateTime> il_create_date { get; set; }
        public Nullable<System.DateTime> il_lastup_date { get; set; }
        public Nullable<bool> il_aktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cari_Adresleri> Cari_Adresleri { get; set; }
    }
}
