//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enti
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ulkeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ulkeler()
        {
            this.Cari_Adresleri = new HashSet<Cari_Adresleri>();
        }
    
        public int ulk_Id { get; set; }
        public string ulk_kod { get; set; }
        public string ulk_adi { get; set; }
        public Nullable<System.DateTime> ulk_create_date { get; set; }
        public Nullable<System.DateTime> ulk_lastup_date { get; set; }
        public Nullable<bool> ulk_aktif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cari_Adresleri> Cari_Adresleri { get; set; }
    }
}
